export const BIST100_SYMBOLS: readonly string[] = [
  "AEFES","AGHOL","AHGAZ","AKBNK","AKCNS","AKFYE","AKSA","AKSEN","ALARK","ALBRK",
  "ALFAS","ANHYT","ARCLK","ASELS","ASTOR","BERA","BIMAS","BRSAN","BRYAT","CANTE",
  "CIMSA","CWENE","DOAS","DOHOL","ECILC","ECZYT","EGEEN","EKGYO","ENERY","ENJSA",
  "ENKAI","EREGL","EUPWR","FROTO","GARAN","GESAN","GLYHO","GUBRF","GWIND","HALKB",
  "HEKTS","ISCTR","ISDMR","ISGYO","ISMEN","KARSN","KAYSE","KCAER","KCHOL","KLSER",
  "KONTR","KRDMD","MAVI","MGROS","MIATK","ODAS","OTKAR","OYAKC","PASEU","PETKM",
  "PGSUS","QUAGR","REEDR","SAHOL","SASA","SISE","SKBNK","SMRTG","SOKM","TABGD",
  "TAVHL","TCELL","THYAO","TKFEN","TOASO","TSKB","TTKOM","TTRAK","TUPRS","ULKER",
  "VAKBN","VESBE","VESTL","YEOTK","YKBNK","ZOREN","AKGRT","ALCTL","ANSGR","BAGFS",
  "BANVT","BJKAS","CCOLA","CEMTS","CLEBI","DESA","FENER","FZLGY","GOODY","KONYA",
];

export const BIST30_SYMBOLS: readonly string[] = [
  "AKBNK","ALARK","ASELS","BIMAS","EKGYO","ENKAI","EREGL","FROTO","GARAN","GUBRF",
  "ISCTR","KCHOL","KOZAL","KOZAA","MGROS","PETKM","PGSUS","SAHOL","SASA","SISE",
  "TCELL","THYAO","TOASO","TUPRS","VAKBN","YKBNK","KRDMD","ENJSA","BRSAN","HALKB",
];
